name = "unita-course"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "unita-course-db"
database_id = "b1e1bcee-0a2a-4f5f-80fb-05e43a8794af"

[vars]
SESSION_SECRET = "unita-learn-secret-2024-production"
